export const THEME_CHANGE = 'THEME_CHANGE';

export const ADD_NOTIFICATION = 'ADD_NOTIFICATION';
export const DELETE_NOTIFICATION = 'DELETE_NOTIFICATION';
export const RESET_NOTIFICATION = 'RESET_NOTIFICATION';
